DAILY CHALLENGE

In [2]:
import pandas as pd

data = pd.read_csv('/content/sample_data/datascience_salaries.csv',index_col=0)
data.dropna()
print(set(data["salary_currency"]))
data

{'USD', 'EUR', 'GBP'}

,job_title,job_type,experience_level,location,salary_currency,salary
0,Data scientist,Full Time,Senior,New York City,USD,149000
2,Data scientist,Full Time,Senior,Boston,USD,120000
3,Data scientist,Full Time,Senior,London,USD,68000
4,Data scientist,Full Time,Senior,Boston,USD,120000
5,Data scientist,Full Time,Senior,New York City,USD,149000
...,...,...,...,...,...,...
2243,ML Ops,Full Time,Senior,Toronto,USD,228000
2249,ML Ops,Full Time,Senior,Boston,USD,115000
2250,ML Ops,Full Time,Senior,Delhi,USD,76000
2255,ML Ops,Full Time,Senior,San Francisco,USD,68000
2259,ML Ops,Internship,Senior,New York City,USD,135000

In [3]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data["salary_normalized"]= scaler.fit_transform(data[['salary']])
print(data[["salary_currency", "salary_normalized"]])

     salary_currency  salary_normalized
0                USD           0.601010
2                USD           0.454545
3                USD           0.191919
4                USD           0.454545
5                USD           0.601010
...              ...                ...
2243             USD           1.000000
2249             USD           0.429293
2250             USD           0.232323
2255             USD           0.191919
2259             USD           0.530303

[1171 rows x 2 columns]

In [8]:
from sklearn.decomposition import PCA

numeric_cols = data.select_dtypes(include=['float64', 'int64']).columns.tolist()
pca = PCA(n_components=2)
components = pca.fit_transform(data[numeric_cols])
data['PCA1'] = components[:, 0]
data['PCA2'] = components[:, 1]

In [9]:
data

,job_title,job_type,experience_level,location,salary_currency,salary,salary_normalized,PCA1,PCA2
0,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010,84163.962426,1.720846e-15
2,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545,55163.962426,1.110223e-15
3,Data scientist,Full Time,Senior,London,USD,68000,0.191919,3163.962425,5.551115e-17
4,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545,55163.962426,1.110223e-15
5,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010,84163.962426,1.720846e-15
...,...,...,...,...,...,...,...,...,...
2243,ML Ops,Full Time,Senior,Toronto,USD,228000,1.000000,163163.962427,3.136380e-15
2249,ML Ops,Full Time,Senior,Boston,USD,115000,0.429293,50163.962426,9.714451e-16
2250,ML Ops,Full Time,Senior,Delhi,USD,76000,0.232323,11163.962425,2.498002e-16
2255,ML Ops,Full Time,Senior,San Francisco,USD,68000,0.191919,3163.962425,5.551115e-17
2259,ML Ops,Internship,Senior,New York City,USD,135000,0.530303,70163.962426,1.471046e-15

In [12]:
resultat = data.groupby('experience_level')['salary'].agg(['mean', 'median'])
print(resultat)

                          mean   median
experience_level
Entry             36111.111111  30000.0
Executive         76076.923077  46000.0
Mid               51786.885246  51000.0
Senior            75088.033012  68000.0